# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'my_testProj' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my_testProj
  pod 'Firebase', '>= 2.5.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

end
